[package]
name = "hf-tokenizer-bridge"
version = "0.1.0"
edition = "2024"
description = "Bridge to use Hugging Face Tokenizers from Golang"
license = "MIT"

[dependencies]
tokenizers = "0.21.1"
serde_json = "1.0"

[lib]
name = "hf_tokenizer_bridge"
crate-type = ["cdylib", "rlib"]